### ISSUE TITLE
Insufficient Unique ID Message when clicking the RDT and Sample Collection Form

### ISSUE THREAD

**Issue by ellyasafaa** [sid-indonesia/rdt-standard#1]
When clicking the RDT Form and Sample Collection Form there is Insufficient Unique ID Message appeared so the form can't be accessed.

1. Go to the home page
2. Click on one of the clients
3. Click the RDT Form or Sample Collection (Pengambilan Sampel) Form
4. See error message: `ID unik tidak cukup. Mohon nyalakan koneksi internet Anda dan lakukan sinkronisasi manual untuk mengambil perintah.`

If we click either RDT or Sample Collection, it is supposed to proceed to the next page

 - Device: Samsung Galazy A50s Android 10; Redmi 5 Plus Android 7

**Comment by sid-yussin** [comment]
Done by setting identifier-source through API.
