### ISSUE TITLE
Android 7: The message of 'Terjadi Masalah Saat Mengurai Paket' popping up when installing the APK

### ISSUE THREAD

**Issue by ellyasafaa** [sid-indonesia/rdt-standard#13]
Android can't be installed on Android 7 devices. I have tried in 4 different devices with different brand, but it didn't work out. There is a message of 'Terjadi Masalah Saat Mengurai Paket' when installing the APK on those devices.

App Version: v1.9.2-CONFIGURABLE-RDT
Download Link: https://drive.google.com/file/d/1A2CSpcf3243B-lA5rCOQqu9ec8bPCFLS/view?usp=drivesdk

Devices:
Galaxy J7+ Android 7.1.1
Redmi 5 Plus Android 7.1.2
Oppo A83 Android 7.1.1
Oppo F5 Android 7.1.1

**Comment by sid-yussin** [comment]
Minimum requirement is Android 8.

**Comment by ellyasafaa** [comment]
Tapi kemarin masih bisa dicoba yang versi ONA di Android 7
